shared: &shared
  adapter: mysql2
  reconnect: true
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password:

development:
  database: funny_movies_dev
  <<: *shared

production:
  database: funny_movies_pro
  <<: *shared

test: &TEST
  database: funny_movies_test
  <<: *shared